import { config, requireElevenLabsServerUrl } from "../config.ts";
import { createElevenLabsClient } from "./client.ts";

const POST_CALL_WEBHOOK_NAME = "alfred-post-call";

/**
 * Ensures a workspace webhook exists for post-call transcription events,
 * pointing at our /webhook/elevenlabs/post-call endpoint. Links it to ConvAI
 * settings so transcript events are sent. Returns the webhook ID and secret.
 *
 * The secret is generated by ElevenLabs on creation and cannot be retrieved
 * later — it must be stored in .env after the first run.
 */
export async function ensurePostCallWebhook(): Promise<{
  webhookId: string;
  webhookSecret: string;
}> {
  const client = createElevenLabsClient();
  const baseUrl = requireElevenLabsServerUrl().replace(/\/$/, "");
  const webhookUrl = `${baseUrl}/webhook/elevenlabs/post-call`;

  // Check if the webhook already exists
  const existingWebhooks = await client.webhooks.list();
  const existing = existingWebhooks.webhooks.find(
    (w) => w.name === POST_CALL_WEBHOOK_NAME,
  );

  let webhookId: string;
  let webhookSecret: string;

  if (existing) {
    // Update the URL in case the server URL changed
    // Note: the SDK doesn't have an update method for workspace webhooks,
    // so we delete and recreate if the URL changed
    if (existing.webhookUrl === webhookUrl) {
      webhookId = existing.webhookId;
      // Secret was only returned on creation — must be in .env
      webhookSecret = config.postCallWebhookSecret ?? "";
      console.log(
        `[post-call] webhook already exists (${webhookId}), URL unchanged`,
      );
    } else {
      console.log(`[post-call] URL changed, recreating webhook...`);
      await client.webhooks.delete(existing.webhookId);
      const created = await client.webhooks.create({
        settings: {
          authType: "hmac",
          name: POST_CALL_WEBHOOK_NAME,
          webhookUrl,
        },
      });
      webhookId = created.webhookId;
      webhookSecret = created.webhookSecret ?? "";
      console.log(
        `[post-call] recreated webhook (${webhookId}), new secret generated`,
      );
    }
  } else {
    console.log("[post-call] creating workspace webhook...");
    const created = await client.webhooks.create({
      settings: {
        authType: "hmac",
        name: POST_CALL_WEBHOOK_NAME,
        webhookUrl,
      },
    });
    webhookId = created.webhookId;
    webhookSecret = created.webhookSecret ?? "";
    console.log(
      `[post-call] created webhook (${webhookId}) → ${webhookUrl}`,
    );
  }

  // Link the webhook to ConvAI settings for transcript events
  await client.conversationalAi.settings.update({
    webhooks: {
      postCallWebhookId: webhookId,
      events: ["transcript"],
    },
  });
  console.log(`[post-call] linked to ConvAI settings (events: transcript)`);

  return { webhookId, webhookSecret };
}
